package org.matveev.pomodoro4nb.prefs;

import javax.swing.JCheckBox;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import static org.matveev.pomodoro4nb.prefs.DefaultPreferencesProvider.*;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 *
 * @author Alexey Matveev
 */
public final class PreferencesDialog extends javax.swing.JPanel {

    private final PreferencesProvider provider;
    
    private PreferencesDialog(PreferencesProvider provider) {
        this.provider = provider;
        initComponents();
        updateComponentsWithPrefs();
    }

    
    public static void createPreferencesDialog(PreferencesProvider provider) {
        PreferencesDialog dialog = new PreferencesDialog(provider);

        NotifyDescriptor descriptor = new NotifyDescriptor(
                dialog,
                "Preferences",
                NotifyDescriptor.OK_CANCEL_OPTION,
                NotifyDescriptor.PLAIN_MESSAGE,
                null,
                NotifyDescriptor.OK_OPTION);

        if (DialogDisplayer.getDefault().notify(descriptor) == NotifyDescriptor.OK_OPTION) {
            dialog.updatePreferences();
        }
    }
    
    private void updateComponentsWithPrefs() {
        enableReminderCheckbox.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                final JCheckBox box = (JCheckBox) e.getSource();
                reminderIntervalSpinner.setEnabled(box.isSelected());
            }
        });
        
        
         pomodoroLengthSpinner.setValue(provider.getInteger(POMODORO_LENGTH_KEY,
                 DefaultPreferencesProvider.DEFAULT_POMODORO_LENGTH));
         shorBreakLengthSpinner.setValue(provider.getInteger(SHORT_BREAK_LENGTH_KEY,
                 DefaultPreferencesProvider.DEFAULT_SHORT_BREAK_LENGTH));
         longBreakLengthSpinner.setValue(provider.getInteger(LONG_BREAK_LENGTH_KEY,
                 DefaultPreferencesProvider.DEFAULT_LONG_BREAK_LENGTH));
         longBreakIntervalSpinner.setValue(provider.getInteger(LONG_BREAK_INTERVAL_KEY,
                 DefaultPreferencesProvider.DEFAULT_LONG_BREAK_INTERVAL));
         enableSoundsCheckbox.setSelected(provider.getBoolean(ENABLE_SOUNDS_KEY, true));
         enableReminderCheckbox.setSelected(provider.getBoolean(ENABLE_REMINDER_KEY, true));

    }
    
    protected void updatePreferences() {
        provider.setInteger(POMODORO_LENGTH_KEY, (Integer) pomodoroLengthSpinner.getValue());
        provider.setInteger(SHORT_BREAK_LENGTH_KEY, (Integer) shorBreakLengthSpinner.getValue());
        provider.setInteger(LONG_BREAK_LENGTH_KEY, (Integer) longBreakLengthSpinner.getValue());
        provider.setInteger(LONG_BREAK_INTERVAL_KEY, (Integer) longBreakIntervalSpinner.getValue());
        provider.setInteger(REMINDER_INTERVAL_KEY, (Integer) reminderIntervalSpinner.getValue());
        provider.setBoolean(ENABLE_SOUNDS_KEY, enableSoundsCheckbox.isSelected());
        provider.setBoolean(ENABLE_REMINDER_KEY, enableReminderCheckbox.isSelected());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pomodoroLengthSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shorBreakLengthSpinner = new javax.swing.JSpinner();
        longBreakLengthSpinner = new javax.swing.JSpinner();
        longBreakIntervalSpinner = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        enableSoundsCheckbox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        enableReminderCheckbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        reminderIntervalSpinner = new javax.swing.JSpinner();

        timingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.timingPanel.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jLabel1.text")); // NOI18N

        pomodoroLengthSpinner.setModel(new javax.swing.SpinnerNumberModel(25, 1, 60, 1));
        pomodoroLengthSpinner.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jLabel4.text")); // NOI18N

        shorBreakLengthSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 60, 1));
        shorBreakLengthSpinner.setPreferredSize(new java.awt.Dimension(50, 20));

        longBreakLengthSpinner.setModel(new javax.swing.SpinnerNumberModel(30, 1, 60, 1));
        longBreakLengthSpinner.setPreferredSize(new java.awt.Dimension(50, 20));

        longBreakIntervalSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 1, 10, 1));
        longBreakIntervalSpinner.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout timingPanelLayout = new javax.swing.GroupLayout(timingPanel);
        timingPanel.setLayout(timingPanelLayout);
        timingPanelLayout.setHorizontalGroup(
            timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pomodoroLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shorBreakLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longBreakLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longBreakIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        timingPanelLayout.setVerticalGroup(
            timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timingPanelLayout.createSequentialGroup()
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pomodoroLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(shorBreakLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(longBreakLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(longBreakIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jPanel1.border.title"))); // NOI18N

        enableSoundsCheckbox.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.enableSoundsCheckbox.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(enableSoundsCheckbox)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(enableSoundsCheckbox)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jPanel2.border.title"))); // NOI18N

        enableReminderCheckbox.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.enableReminderCheckbox.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(PreferencesDialog.class, "PreferencesDialog.jLabel5.text")); // NOI18N

        reminderIntervalSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));
        reminderIntervalSpinner.setMinimumSize(new java.awt.Dimension(60, 20));
        reminderIntervalSpinner.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(enableReminderCheckbox)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminderIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(enableReminderCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(reminderIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox enableReminderCheckbox;
    private javax.swing.JCheckBox enableSoundsCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner longBreakIntervalSpinner;
    private javax.swing.JSpinner longBreakLengthSpinner;
    private javax.swing.JSpinner pomodoroLengthSpinner;
    private javax.swing.JSpinner reminderIntervalSpinner;
    private javax.swing.JSpinner shorBreakLengthSpinner;
    private javax.swing.JPanel timingPanel;
    // End of variables declaration//GEN-END:variables
}
